# Generated by Django 4.2.4 on 2023-09-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_accession', models.CharField(max_length=255)),
                ('nom_accession', models.CharField(max_length=255)),
                ('type_accession', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('genre', 'Genre'), ('espèce', 'Espèce')], max_length=255)),
                ('anciennete', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristiquesArbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_caracteristique_arbre', models.CharField(max_length=255)),
                ('port', models.CharField(choices=[('etale', 'Etale'), ('dresse', 'Dressé'), ('dresse-a-etale', 'Dressé à Etale')], max_length=255)),
                ('vigueur', models.CharField(choices=[('moyenne', 'Moyenne'), ('faible', 'Faible'), ('vigoureuse', 'Vigoureuse')], max_length=255)),
                ('floraison', models.CharField(max_length=255)),
                ('epoque', models.CharField(choices=[('debut-mois', 'Début Mois'), ('mi-mois', 'Mi-Mois'), ('fin-mois', 'Fin Mois')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristiquesFruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_caracteristique_fruits', models.CharField(max_length=255)),
                ('forme_de_fruit', models.CharField(max_length=255)),
                ('couleur_peau', models.CharField(max_length=255)),
                ('couleur_chair', models.CharField(max_length=255)),
                ('poids', models.CharField(max_length=255)),
                ('teneur_de_sucre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseHerberium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe_herberium', models.CharField(max_length=255)),
                ('numero_etagere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cultivars', models.CharField(max_length=255)),
                ('traduction', models.CharField(max_length=255)),
                ('synonyme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fruit', models.CharField(max_length=255)),
                ('taille', models.CharField(max_length=255)),
                ('forme', models.CharField(max_length=255)),
                ('poids_moyenne', models.CharField(max_length=255)),
                ('maturite', models.CharField(max_length=255)),
                ('aspect_surface', models.CharField(max_length=255)),
                ('calibre', models.CharField(max_length=255)),
                ('chair', models.CharField(max_length=255)),
                ('teneur', models.CharField(max_length=255)),
                ('autres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_caracteristique', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('taille', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_collection', models.CharField(max_length=255)),
                ('adresse_origine', models.CharField(max_length=255)),
                ('nom_collecteur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_arbre', models.CharField(max_length=255)),
                ('numero_collection', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SemenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.accession')),
                ('caracteristiques_fruits', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.caracteristiquesfruits')),
                ('classe_herberium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classeherberium')),
                ('cultivars', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cultivars')),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observation')),
                ('origine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.origine')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristiques_arbre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.caracteristiquesarbre')),
                ('fruit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.fruit')),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.parcelle')),
            ],
        ),
    ]
