# Generated by Django 5.0.2 on 2024-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('culture', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization_farm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='profiles/')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_wells', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('electricity_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('measure', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_measure', models.DateField()),
                ('zone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('battery_lvl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numero_zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pumps', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='semencegroup',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='parcellegroup',
            name='caracteristiques_arbre',
        ),
        migrations.RemoveField(
            model_name='semencegroup',
            name='caracteristiques_fruits',
        ),
        migrations.RemoveField(
            model_name='semencegroup',
            name='classe_herberium',
        ),
        migrations.RemoveField(
            model_name='semencegroup',
            name='cultivars',
        ),
        migrations.RemoveField(
            model_name='parcellegroup',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='semencegroup',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='semencegroup',
            name='origine',
        ),
        migrations.RemoveField(
            model_name='parcellegroup',
            name='parcelle',
        ),
        migrations.DeleteModel(
            name='Accession',
        ),
        migrations.DeleteModel(
            name='CaracteristiquesArbre',
        ),
        migrations.DeleteModel(
            name='CaracteristiquesFruits',
        ),
        migrations.DeleteModel(
            name='ClasseHerberium',
        ),
        migrations.DeleteModel(
            name='Cultivars',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Origine',
        ),
        migrations.DeleteModel(
            name='SemenceGroup',
        ),
        migrations.DeleteModel(
            name='Parcelle',
        ),
        migrations.DeleteModel(
            name='ParcelleGroup',
        ),
    ]
