# Generated by Django 5.0.2 on 2024-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_agriculturalzone_alarm_farm_farmer_map_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('treated', 'Treated'), ('not_treated', 'Not Treated')], max_length=20)),
                ('taille', models.IntegerField()),
            ],
        ),
    ]
